# Generated by Django 2.2.6 on 2020-01-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
