# Generated by Django 2.2.6 on 2020-01-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='customerid',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
